### ISSUE TITLE
Pchat forgets default tab now

### ISSUE THREAD

**Issue by vantheguitarman** [Baertram/pChat#14]
Hi there!
Just letting you know on multiple computers Pchat forgets the set default tab to land on.
Cheers and love your work
V

**Comment by Baertram** [comment]
Please tell me what tabs you use (screenshot at best) and what your setting for the default tab is, and what it actually sets the tab to then (the bug).
Is it happening directly at login? At each reload UI?

Thank you

**Comment by Baertram** [comment]
Found the bug and am working on a fix
