### ISSUE TITLE
Stuck on Whisper

### ISSUE THREAD

**Issue by vantheguitarman** [Baertram/pChat#16]
Hi there!
Great addon, little issue though where once I have whispered somebody, that is then my default tab no matter which tab I select, it is only whisper that does this.
Work around is I click on persons name then change to another tab, then it auto-selects again

**Comment by Baertram** [comment]
Hi, thanks for the feedback.

What tabs do you use and is your whisper tan only setup for whispers? 

What did you choose for the default tab in pchat settings? 

Are any other addons enabled as this happens? Please disable all others and test of this still happens. If not please find kurzout which other addons are causing this. 


Could you please describe with more detail how to reproduce this bug, from login/reloadui to the problem, on simple steps:
Login
Select whisper tab
Write text and send
... 

Thank you

**Comment by Baertram** [comment]
@vantheguitarman Any update on that, please answer my questions or provide more details/steps from login to the problem so I can rebuild it and have a look how/if there is a fix.

Thank you

**Comment by Baertram** [comment]
@vantheguitarman If the issue still happening disable all other addons and try with pChat alone please. If this still got the issue describe wth more detials "in a new opened issue" please.

Thank you

**Comment by vantheguitarman** [comment]
Hi there! Sorry I didn't get an email notification that you had replied, I fixed this by selecting: Remember last channel
Then it goes back to the default channel for each tab, I just have to change tabs. Thank you!
