### ISSUE TITLE
Can't whisper or type in group chat

### ISSUE THREAD

**Issue by Valkyrwyn** [Baertram/pChat#18]
Since the Gold Road update, I have been unable to whisper anyone or type in group chat while pchat is enabled. I type in the chat box, hit enter, and the text just disappears. Initially I thought I had a social ban for some reason - it took a while to get a response from the ESO ticket team, but they confirmed I didn't have a ban and suggested an add on issue.
I've finally tracked it down to pchat. I turn off pchat, the problem goes away. I have uninstalled pchat and its saved variables and reinstalled from scratch - same thing happens. 
I'm currently playing without pchat, but I miss having @names instead of character names and not having timestamps. I'd love to be able to work out what's happening and why. I don;t have any alt hotkeys bound.

**Comment by Baertram** [comment]
Hi there, that's not a common issue and I guess you got any other addon enabled that interferes then.
Someone in my guild had a similar problem and he sad it was another addon (cannot remember which one though) which was causing it.

Please disbale ALL addons and test only wth pChat alone.
If you did that already please make sure to try this:
1. logout
2. delete live/AddOns/pChat
3. Download pChat manually (not via Minion!) here
https://www.esoui.com/downloads/dl93/pChat_baertram_10_0_5_3.zip?171786537815
and extract "only the pChat" folder from the zip file to live/AddOns so you got /live/AddOns/pChat/pChat.txt and other folders  and files
Check if your Antivirus blocks extraction of some pChat files from the zip file? Compare that all files and folders in the zip are there in live/AddOns/pChat
Allow live/AddOns in your Antivirus program.

If you use AVAST, read here:
https://www.esoui.com/forums/showthread.php?t=10988&highlight=avast
4. Do the same for ALL libraries that pChat needs, update them all manually and remove them before updating! -> Do not overwrite existing folders.
5.  Backup the file live/SavedVariables/pChat.lua -> rename to pChat_backup.lua e.g. This resets pChat settings and clears history
6. Login and at charatcer selection disable ALL addons except pChat and the needed dependencies
7. Login to teh ingame world and see if that fixed it.
Press ESC and check at AddOns if only pChat and needed dependencies are enabled! If not disable other addons which go enabled there and reloadui!

If that all does not help I'm not sure what else to do.
I hope it fixes that for you.

**Comment by Baertram** [comment]
Maybe this is related to the AntiSpam otions of pchat but you'd have to write something like lf or wts or sell or sale and gol or crown in the chat message.

I'll close this issue here now as noone else reported similar issues, and I think you got some broken SavedVariables and need to reset them, or any other older library/AddOn you are using is causing this.
