### ISSUE TITLE
@Username/Charname 

### ISSUE THREAD

**Issue by FLY1NGSQU1RR3L** [Baertram/pChat#8]

**Comment by FLY1NGSQU1RR3L** [comment]
**First off, thank your for this addon.**  
I can never go back to stock chat window.  The little quality of life improvements are just amazing.

**Having a little problem**
1. Post-patch, pChat is no longer supporting @username/charname for me in every channel.
2. Additionally, the settings seem to fluctuate between /reloadui, map changes, and logins on every channel.
3. It is defaulting to Charname in almost every case, but I've gotten in a situation where /s and /z were working, but /g1 and /g were not.

**Troubleshooting*
I completely wiped out my add-ons folder and went through several login/logout cycles to make 1000% sure all of my mods were removed.  I manually reinstalled the mod from this repo and the latest commits, then grabbed the dependencies from Minion.  

No change.  If anything, it got a little worse.

**Comment by Baertram** [comment]
Hey, last update fixed this. Thanks for the detailed info!

**Comment by FLY1NGSQU1RR3L** [comment]
Would grabbing the Minion Build or the GitHub build fix this?  I did so at the time of reporting (21hrs ago) so just wondering if I'm not properly resetting my pChat mod :)

**Comment by FLY1NGSQU1RR3L** [comment]
Confirmed, I just went through the clean install procedure again and it's still broken.  Is there a repository on my system somewhere that could be caching the old version or a file that is causing this?

**Comment by Baertram** [comment]
Hm, not that I could know, it's your pc :-)
Maybe you update the addons folder but the game thinks another folder is the correct on. Sometimes MS windows defneder updates all of sudden move the ES game to think the addons folder is no longer in c:\users\...\documents\elder scrolls online\live\addons but c.\programdata\elder scrolls addon\live\addons (or similar).

You can test this by logging in, tkae a screenshot and watch at the top right screen edge: The folder shown /Screenshots got a parent folder and this is where the game expects the /AddOns folder to be!
Check if this is the folder where you have updated your addons currently to.

Else make sure to manually delete the folder /AddOns/pChat completely and try to manually install the most recent version from esoui (not GitHub!): https://www.esoui.com/downloads/info93-pChat.html
Version 10.0.2.5 fixes the guild and other settings for all other users so I really wonder why it should not work for you :-(

If it still does not work please do a fresh install, change the settings and reloadui (until the error happens), then logout. Send me your /live/SavedVariables/pChat.lua file to baertram.esoui@gmx.net (maybe zip it to reduce size) and tell me:
What did you do in steps/details from fresh install to the error and what is the Server and @accountName + CharName you play the game with as the error happens.
I'll test with your SV files then and try to reproduce it.

**Comment by FLY1NGSQU1RR3L** [comment]
Did another complete wipe + reload of my add-ons folder and your steps above 100% fixed it.  It's insane how bad a state I was in.  Several other mods were not updating either and I had no idea they weren't working properly.

**Comment by Baertram** [comment]
You are welcome ;-)
